- name: System | oh-my-zsh | add oh-my-zsh
  ansible.builtin.include_role:
    name: gantsign.oh-my-zsh
  vars:
    users: 
      - username: "{{ user_name }}"
        oh_my_zsh:
          plugins:
            - git
            - nvm
            - pyenv
            - aliases
          install: true

- name: System | oh-my-zsh | clone powerlevel10k
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    depth: 1
    dest: $HOME/.oh-my-zsh/custom/themes/powerlevel10k
  become: true
  become_user: "{{ user_name }}"

- name: System | oh-my-zsh | update zsh file
  ansible.builtin.lineinfile:
    path: /home/{{ user_name }}/.zshrc
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
    state: present
    backup: 'yes'
  become: true
  become_user: "{{ user_name }}"

# still need to download the font
- name: System | oh-my-zsh | Create fonts directory
  become: true
  file:
    path: "/usr/share/fonts/TTF/"
    mode: '0755'
    state: directory

- name: System | oh-my-zsh | Copy powerlevel10k recommanded fonts
  become: true
  copy:
    src: "fonts/{{ item }}"
    dest: "/usr/share/fonts/TTF/{{ item }}"
    mode: '0755'
  loop:
    - MesloLGS NF Bold Italic.ttf
    - MesloLGS NF Bold.ttf
    - MesloLGS NF Italic.ttf
    - MesloLGS NF Regular.ttf