- name: Git repos | ESP-IDF | make esp directory
  ansible.builtin.file:
    path: ~/esp
    state: directory
    mode: '0755'

- name: Git repos | ESP-IDF | clone esp-idf
  ansible.builtin.git:
    repo: https://github.com/espressif/esp-idf.git
    dest: ~/esp/esp-idf
    recursive: true
    force: true
  become: true


- name: Git repos | ESP-IDF | set up IDF tools
  ansible.builtin.shell: |
    cd ~/esp/esp-idf
    ./install.sh all
  become: true

# not sure if this one is needed
- name: Git repos | ESP-IDF | set up env variables
  ansible.builtin.shell:
    cmd: . ~/esp/esp-idf/export.sh
  become: "{{ user_name }}"
