- name: git repos | ESP-IDF | make esp directory
  file:
    path: ~/esp
    state: directory
    mode: '0755'

- name: git repos | ESP-IDF | clone esp-idf
  git: 
    repo: https://github.com/espressif/esp-idf.git 
    dest: ~/esp/esp-idf
    recursive: true    
    force: true


- name: git repos | ESP-IDF | set up IDF tools
  shell: |
    cd ~/esp/esp-idf
    ./install.sh all
  become: yes
  become_user: "{{ user_name }}"
  become_method: sudo

# not sure if this one is needed
- name: git repos | ESP-IDF | set up env variables
  shell: |
    . $HOME/esp/esp-idf/export.sh
  become: yes
  become_user: "{{ user_name }}"
  become_method: sudo
