roles:
# needed for VS code
- name: gantsign.visual-studio-code

# needed for VS code extensions
- name: gantsign.visual-studio-code-extensions

# needed for oh-my-zsh
- name: gantsign.oh-my-zsh


collections:
# needed for snapd
  - name: community.general
    source: https://galaxy.ansible.com
