# not working yet

- name: Software | 1pass | add 1pass key
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/keys/1password.asc
    dest: /usr/share/keyrings/1password-archive-keyring.asc
    mode: 0644
    force: true
  become: true


- name: Software | 1pass | add 1pass repo
  tags: 1password,software
  ansible.builtin.apt_repository:
    filename: 1password
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.asc] https://downloads.1password.com/linux/debian/amd64 stable main'
    state: present
  become: true


- name: Software | 1pass | install package
  tags: 1password,software
  ansible.builtin.apt:
    name: 1password
    state: latest
    update_cache: true
  become: true
