# add alacritty to apt repo
- name: Software | alacritty | add alacritty key
  tags: alacritty,software
  become: true
  apt_repository:
    repo: ppa:aslatter/ppa
    state: present
    filename: alacritty

- name: software | alacritty | install package
  ansible.builtin.apt:
    name: alacritty
    state: latest