- name: Software | Slack | install slack
  tags: packages,slack,snap,notest
  community.general.snap:
    classic: true
    name: slack
    state: present
  become: true
  when: ansible_distribution != "Archlinux"
