- name: software | spotify | add spotify key
  ansible.builtin.get_url:
    url: https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
    dest: /etc/apt/trusted.gpg.d/spotify.asc
    mode: 0644
    force: true


- name: software | spotify | add spotify repo
  tags: spotify,software
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    filename: spotify
  register: spotify_repo

- name: software | spotify | install package
  tags: spotify,software
  apt:
    name: spotify-client
    state: latest
  when: spotify_repo is changed
