# not working yet
- name: Software | steam | accept license
  tags: gaming,steam
  debconf:
    name: "steam"
    question: "steam/question"
    value: "I AGREE"
    vtype: "select"
  when:
    - ansible_distribution in ["Debian", "Ubuntu"]
    - steam is defined
    - steam == true

- name: Software | steam | install package
  tags: steam,steam
  ansible.builtin.package:
    state: latest
    name: "{{ steam_package }}"
  when:
    - steam is defined
    - steam == true

- name: Software | steam | install steam-devices package (debian, ubuntu, etc)
  tags: steam,steam
  ansible.builtin.package:
    state: latest
    name: steam-devices
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - steam is defined
    - steam == true

- name: Install vulkan drivers (debian, ubuntu, etc)
  tags: drivers,steam
  ansible.builtin.package:
    state: latest
    name: mesa-vulkan-drivers
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - steam is defined
    - steam == true