# - name: software | virtualbox | install apt key (debian)
#   tags: virtualbox,repositories,virtualbox
#   apt_key:
#     url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
#     state: present
#   # when:
#   #   - ansible_distribution == "Debian"
#   #   - virtualbox is defined
#   #   - virtualbox == true

# - name: software | virtualbox | install repository (debian)
#   tags: virtualbox,repositories,virtualbox
#   apt_repository:
#     repo: deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian jammy contrib
#     state: present
#     filename: virtualbox
#   register: virtualbox_repo_debian
#   # when:
#   #   - ansible_distribution == "Debian"
#   #   - virtualbox is defined
#   #   - virtualbox == true

# - name: software | virtualbox | install package
#   tags: virtualbox
#   package:
#     name: virtualbox-6.1
#   # when:
#   #   - virtualbox is defined
#   #   - virtualbox == true



- name: software | virtualbox | install apt key (debian)
  ansible.builtin.get_url:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    dest: /usr/share/keyrings/oracle-virtualbox-2016.asc

- name: software | virtualbox | install repository (debian)
  tags: virtualbox,repositories,virtualbox
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.asc] https://download.virtualbox.org/virtualbox/debian jammy contrib
    state: present
    filename: virtualbox
  register: virtualbox_repo_debian

- name: software | virtualbox | install package
  tags: virtualbox
  package:
    name: virtualbox-6.1