# set up flatpak support
- name: System setup | package managers | add flatpak support
  ansible.builtin.package:
    name: flatpak
    state: present
  become: true
  # become_user: "{{ user_name }}"

- name: System setup | package managers | add flathub remote
  tags: packages,flatpak
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
    state: present
