# set up flatpak support
- name: System setup | package managers | add flatpak support
  ansible.builtin.package:
    name: flatpak
    state: present

- name: System setup | package managers | add flathub remote
  tags: packages,flatpak
  ansible.builtin.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
    state: present
