# install snap
- name: System setup | package managers | install snapd
  ansible.builtin.package:
    name: snapd
    state: latest
  become: true
  when: ansible_distribution != "Archlinux"

# # Ensure core snap is installed
# - name: System setup | package managers | install/update core snap
#   tags: packages,snap,todoist,workstation-packages
#   snap:
#     name:  core
#     state: present
#   when: ansible_distribution != "Archlinux"
