- name: Software | nvm | Make nvm project folder
  file:
    path: "{{ local_home  }}/.nvm"
    state: directory
    mode: '0755'

- name: Software | nvm | clone nvm
  ansible.builtin.git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "{{ local_home  }}/.nvm"
    version: v0.39.3

- name: Software | nvm | source nvm
  ansible.builtin.shell: |
    . {{ local_home }}/.nvm/nvm.sh
  args:
    executable: /bin/zsh
  become_user: "{{ user_name }}"

- name: Software | nvm | add nvm path
  ansible.builtin.lineinfile:
    path: "~/.zshrc"
    insertafter: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
    backup: true
  loop:
    - { regexp: '^export ZSH=', line: '# Path to nvm' }
    - { regexp: '^# Path to nvm', line: 'export NVM_DIR="$HOME/.nvm"' }
    - { regexp: '^export NVM_DIR', line: '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm' }
  become_user: "{{ user_name }}"

- name: Software | nvm | install latest Node
  ansible.builtin.shell: |
    . {{ local_home }}/.nvm/nvm.sh && nvm install node
  args:
    executable: /bin/zsh
    chdir: "$HOME"
    creates: "$HOME/.nvm/versions/node/n{{ item }}"
  loop:
    - node
  become_user: "{{ user_name }}"

- name: Software | nvm | create ~/.npmrc
  ansible.builtin.file:
    path: "~/.npmrc"
    state: touch
    mode: '0644'
  become_user: "{{ user_name }}"

- name: Software | nvm | add npm token
  ansible.builtin.lineinfile:
    path: "~/.npmrc"
    insertafter: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
    backup: true
  loop:
    - { regexp: '', line: '//registry.npmjs.org/:_authToken={{ npm_token }}' }
    - { regexp: '', line: '@mysa:registry=https://registry.npmjs.org/' }
  become_user: "{{ user_name }}"

- name: Software | nvm | source /.zshrc"
  ansible.builtin.shell:
    cmd: source ~/.zshrc
  args:
    executable: /bin/zsh
  become_user: "{{ user_name }}"

