# - name: Languages | Rust | check if cargo is installed
#   ansible.builtin.shell:
#     cmd: cargo --version
#   failed_when: "'not found' in command_result.stderr"
#   register: cargo_exists
#   ignore_errors: true

- name: Languages | rust | Download Installer
  when: cargo_exists is failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust
  become: true

- name: Languages | Rust | install rust/cargo
  ansible.builtin.shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
  # when: cargo_exists is failed
