- name: Languages | Rust | check if cargo is installed
  ansible.builtin.shell: command -v cargo
  register: cargo_exists
  ignore_errors: true

- name: Languages | rust | Download Installer
  when: cargo_exists is failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: Languages | Rust | install rust/cargo
  ansible.builtin.shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
  when: cargo_exists is failed
